version: '3.9'
services:
  microservice-template:
    build: .
    container_name: microservice-template
    ports:
      - '443:443'
    environment:
      - spring.datasource.url=
      - spring.datasource.username=
      - spring.datasource.password=
      - spring.profiles.active=
      - spring.elasticsearch.rest.uris=
      - spring.kafka.bootstrapServers=
      - spring.redis.host=
      - cloud.aws.credentials.useDefaultAwsCredentialsChain=
      - cloud.aws.credentials.accessKey=
      - cloud.aws.credentials.secretKey=
      - cloud.aws.region.static=
      - cloud.aws.region.useDefaultAwsRegionChain=
      - cloud.aws.stack.auto=
    networks:
      - postgres_network
      - redis_network
      - kafka_network
      - elastic_network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
    mem_limit: 536870912
    cpus: 0.25

networks:
  postgres_network:
    name: postgres_network
    external: true
  redis_network:
    name: redis_network
    external: true
  kafka_network:
    name: kafka_network
    external: true
  elastic_network:
    name: elastic_network
    external: true
