services:
  spring-template:
    build:
      context: .
      platforms:
        - linux/arm64
        - linux/amd64
      args:
        SPRING_PROFILES_ACTIVE: local
    container_name: spring-template
    restart: unless-stopped
    depends_on:
      - elasticsearch
      - postgres
      - redis
      - kafka
      - jaeger
    ports:
      - "80:80"
    env_file: .docker.env
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost/actuator/health || exit 1" ]
    deploy:
      resources:
        reservations:
          memory: 512M
          cpus: "0.25"
        limits:
          memory: 512M
          cpus: "0.25"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    container_name: elasticsearch-template
    environment:
      ELASTIC_PASSWORD: 12345678
      ES_JAVA_OPTS: -Xms256m -Xmx512m
      discovery.type: single-node
      bootstrap.memory_lock: true
      xpack.security.transport.ssl.enabled: false
  postgres:
    image: postgres:15-alpine
    container_name: postgres-template
    environment:
      POSTGRES_DB: spring_template
      POSTGRES_PASSWORD: 12345678
  redis:
    image: redis:6-alpine
    container_name: redis-template
  kafka:
    image: confluentinc/cp-kafka:7.5.3
    container_name: kafka-template
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-template:19092,PLAINTEXT_HOST://localhost:9092
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-template:9093
      KAFKA_LISTENERS: PLAINTEXT://kafka-template:19092,CONTROLLER://kafka-template:9093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_HEAP_OPTS: -Xms128m -Xmx256m
      CLUSTER_ID: DwulslKcTFOZ1R8bCya7Vg
  jaeger:
    image: jaegertracing/all-in-one:1
    container_name: jaeger-template
    depends_on:
      - elasticsearch
