version: "3.9"
services:
  spring-template:
    build: .
    container_name: spring-template
    ports:
      - "443:443"
    env_file: .docker.env
    networks:
      - postgres_network
      - redis_network
      - kafka_network
      - elasticsearch_network
      - zipkin_network
    deploy:
      resources:
        reservations:
          memory: 512M
          cpus: "0.25"
        limits:
          memory: 512M
          cpus: "0.25"

networks:
  postgres_network:
    name: postgres_network
    external: true
  redis_network:
    name: redis_network
    external: true
  kafka_network:
    name: kafka_network
    external: true
  elasticsearch_network:
    name: elasticsearch_network
    external: true
  zipkin_network:
    name: zipkin_network
    external: true
