services:
  spring-template:
    build:
      context: .
      platforms:
        - linux/arm64
        - linux/amd64
    container_name: spring-template
    restart: unless-stopped
    ports:
      - "80:80"
    env_file: .docker.env
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost/actuator/health || exit 1" ]
    deploy:
      resources:
        reservations:
          memory: 512M
          cpus: "0.25"
        limits:
          memory: 512M
          cpus: "0.25"
    depends_on:
      - elasticsearch
      - postgres
      - redis
      - kafka
      - zipkin
      - ollama
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    container_name: elasticsearch-template
    environment:
      ELASTIC_PASSWORD: 12345678
      ES_JAVA_OPTS: -Xms256m -Xmx512m
      discovery.type: single-node
      bootstrap.memory_lock: true
      xpack.security.transport.ssl.enabled: false
  postgres:
    image: pgvector/pgvector:pg17
    container_name: postgres-template
    environment:
      POSTGRES_DB: spring_template
      POSTGRES_PASSWORD: 12345678
  redis:
    image: redis:7-alpine
    container_name: redis-template
  kafka:
    image: apache/kafka-native:3.9.1
    container_name: kafka-template
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-template:19092,PLAINTEXT_HOST://localhost:9092
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-template:9093
      KAFKA_LISTENERS: PLAINTEXT://kafka-template:19092,CONTROLLER://kafka-template:9093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
  zipkin:
    image: openzipkin/zipkin-slim:3
    container_name: zipkin-template
  ollama:
    image: ollama/ollama:0.11.4
    container_name: ollama-template
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    entrypoint:
      - /bin/sh
      - -c
      - |
        ollama serve &
        pid=$!
        sleep 5
        ollama pull llama3.1
        ollama pull all-minilm
        wait $pid
