version: '3.9'
services:
  microservice-template:
    build: .
    container_name: microservice-template
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:5432/spring_microservice
      - spring.datasource.username=
      - spring.datasource.password=
      - spring.profiles.active=local,aws
      - spring.security.oauth2.resourceserver.jwt.jwkSetUri=https://leijendary.us.auth0.com/.well-known/jwks.json
      - spring.kafka.properties.schema.registry.url=http://schema-registry:8081
      - spring.kafka.bootrapServers=kafka:29092
      - spring.redis.host=redis
      - spring.elasticsearch.rest.uris=http://elasticsearch:9200
      - cloud.aws.credentials.accessKey=
      - cloud.aws.credentials.secretKey=
      - cloud.aws.region.static=
    networks:
      - postgres_network
      - redis_network
      - kafka_network
      - elastic_network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M

networks:
  postgres_network:
    name: postgres_network
    external: true
  redis_network:
    name: redis_network
    external: true
  kafka_network:
    name: kafka_network
    external: true
  elastic_network:
    name: elastic_network
    external: true