#!/bin/sh

./gradlew clean bootJar -x test

set -a
. ./.local.env
set +a

java -Dspring.aot.enabled=true \
  -agentlib:native-image-agent=config-output-dir=src/main/resources/META-INF/native-image \
  -jar build/libs/*.jar
