aws:
  cloudFront:
    distributionId:
    url: https://cdn.dev.leijendary.com
  s3:
    bucketName: leijendary-api-dev

logging:
  includeApplicationName: false
  pattern:
    correlation:

management:
  tracing:
    enabled: false
    sampling:
      probability: 1.0

spring:
  cloud:
    aws:
      cloudwatch:
        enabled: false
  data:
    redis:
      ssl:
        enabled: false
  kafka:
    jaas:
      enabled: false
    properties:
      sasl:
        mechanism: PLAIN
    security:
      protocol: PLAINTEXT
  output:
    ansi:
      enabled: ALWAYS
