encrypt:
  key: EFFbUfV4BB250GznmHdiQ1eYr79q8zSskPAmzVPe/k8=
  salt: 08dbf175cbeb91f3

spring:
  datasource:
    primary:
      jdbcUrl: jdbc:postgresql://localhost:5432/spring_template
      username: postgres
      password: 12345678
    readonly:
      jdbcUrl: jdbc:postgresql://localhost:5432/spring_template
      username: postgres
      password: 12345678
  data:
    redis:
      host: localhost
      port: 6379
  elasticsearch:
    uris: http://localhost:9200
  kafka:
    bootstrapServers: localhost:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          issuerUri: https://leijendary.eu.auth0.com/
          jwkSetUri: https://leijendary.eu.auth0.com/.well-known/jwks.json
          audiences: http://localhost:8000

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
