info:
  app:
    organization: leijendary
    group: ${group}
    name: ${name}
    description: ${description}
    version: ${version}
  api:
    termsOfService:
    contact:
      name: Jonathan Leijendekker
      url: https://leijendary.com
      email:
    license:
      name: Jonathan Leijendekker
      url: https://leijendary.com

auth:
  anonymousUser:
    principal: Anonymous User
  system:
    principal: System

emission:
  deadline: 5m

encrypt:
  key:
  salt:

number:
  scale: 2
  round: HALF_UP

retry:
  maxAttempts: 3
  backoff:
    delay: 5
    maxDelay: 20
    multiplier: 2

spring:
  application:
    name: \${info.app.name}
  main:
    bannerMode: log
  datasource:
    primary:
      poolName: Primary
      jdbcUrl:
      username:
      password:
      dataSourceProperties:
        cachePrepStmts: true
        rewriteBatchedStatements: true
        useServerPrepStmts: true
      maximumPoolSize: 20
    readonly:
      poolName: Read-only
      jdbcUrl:
      username:
      password:
      maximumPoolSize: 5
  data:
    jdbc:
      repositories:
        enabled: false
    ldap:
      repositories:
        enabled: false
    redis:
      repositories:
        enabled: false
      host:
      port:
    web:
      pageable:
        maxPageSize: 100
  devtools:
    livereload:
      port: 35730
  jpa:
    openInView: false
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
      jakarta:
        persistence:
          lock:
            timeout: 2000
          sharedCache:
            mode: UNSPECIFIED
  messages:
    basename: messages.access, messages.error, messages.validation
  mvc:
    throwExceptionIfNoHandlerFound: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuerUri:
          jwkSetUri:
          audiences:
  task:
    execution:
      pool:
        coreSize: 100
    scheduling:
      pool:
        size: 100
  web:
    resources:
      addMappings: false
  cache:
    type: redis
    redis:
      timeToLive: 5h
  cloud:
    discovery:
      client:
        simple:
          instances:
            sample:
              - uri: https://google.com
    loadbalancer:
      retry:
        maxRetriesOnSameServiceInstance: 3
        retryOnAllOperations: true
        retryableStatusCodes:
          - 502
          - 503
        backoff:
          enabled: true
          minBackoff: \${retry.backoff.delay}ms
          maxBackoff: \${retry.backoff.maxDelay}ms
          jitter: \${retry.backoff.multiplier}
    serviceRegistry:
      autoRegistration:
        enabled: false
    function:
      definition: sampleCreate;sampleUpdate;sampleDelete;sampleCreated;sampleUpdated;sampleDeleted
    stream:
      bindings:
        sampleCreate-out-0:
          destination: \${info.app.organization}.sample.create
        sampleCreated-in-0:
          destination: \${info.app.organization}.sample.create
        sampleUpdate-out-0:
          destination: \${info.app.organization}.sample.update
        sampleUpdated-in-0:
          destination: \${info.app.organization}.sample.update
        sampleDelete-out-0:
          destination: \${info.app.organization}.sample.delete
        sampleDeleted-in-0:
          destination: \${info.app.organization}.sample.delete
      default:
        group: \${info.app.name}
      kafka:
        binder:
          enableObservation: true
        default:
          consumer:
            enableDlq: true
        streams:
          binder:
            autoAddPartitions: true
            deserializationExceptionHandler: sendToDlq
            functions:
              sampleCreate:
                applicationId: \${info.app.name}.\${spring.cloud.stream.bindings.sampleCreate-out-0.destination}
              sampleCreated:
                applicationId: \${info.app.name}.\${spring.cloud.stream.bindings.sampleCreated-in-0.destination}
              sampleUpdate:
                applicationId: \${info.app.name}.\${spring.cloud.stream.bindings.sampleUpdate-out-0.destination}
              sampleUpdated:
                applicationId: \${info.app.name}.\${spring.cloud.stream.bindings.sampleUpdated-in-0.destination}
              sampleDelete:
                applicationId: \${info.app.name}.\${spring.cloud.stream.bindings.sampleDelete-out-0.destination}
              sampleDeleted:
                applicationId: \${info.app.name}.\${spring.cloud.stream.bindings.sampleDeleted-in-0.destination}
  elasticsearch:
    uris:
    username:
    password:
  kafka:
    bootstrapServers:
    properties:
      interceptor:
        classes: com.leijendary.spring.template.core.interceptor.KafkaLoggingInterceptor
    producer:
      properties:
        spring:
          json:
            add:
              type:
                headers: false

server:
  error:
    whitelabel:
      enabled: false
  http2:
    enabled: true
  port: 443
  ssl:
    enabled: true
    keyAlias: spring-boot
    keyStoreType: PKCS12
    keyStore: classpath:ssl/keystore.p12
    keyStorePassword: spring-boot
  tomcat:
    threads:
      max: 1000

springdoc:
  pathsToMatch: /api/**
  swaggerUi:
    disableSwaggerDefaultUrl: true

management:
  endpoint:
    health:
      showDetails: ALWAYS
  endpoints:
    web:
      exposure:
        include: health, prometheus
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint:

logging:
  level:
    liquibase:
      hub: ERROR
    org:
      apache:
        kafka: ERROR
      springframework:
        data:
          elasticsearch:
            support:
              VersionInfo: ERROR
  pattern:
    level: '%5p [\${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
