aws:
  cloudFront:
    distributionId:
    url: https://cdn.dev.leijendary.com
  s3:
    bucketName: leijendary-api-dev

logging:
  includeApplicationName: false

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  data:
    redis:
      ssl:
        enabled: false
  kafka:
    jaas:
      enabled: false
    properties:
      sasl:
        mechanism: PLAIN
    security:
      protocol: PLAINTEXT
