spring:
  cloud:
    aws:
      cloudFront:
        distributionId:
        url: https://cdn.leijendary.com
      s3:
        bucketName: leijendary-api-prod
  kafka:
    listener:
      concurrency: 10
    topic:
      sampleCreated:
        partitions: 5
      sampleUpdated:
        partitions: 3
      sampleDeleted:
        partitions: 2

springdoc:
  apiDocs:
    enabled: false
  swaggerUi:
    enabled: false
