server:
  port: 8443

management:
  endpoint:
    health:
      showDetails: ALWAYS

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR
    io:
      netty:
        resolver:
          dns:
            DnsServerAddressStreamProviders: OFF