auth:
  audience: https://leijendary.com

spring:
  main:
    bannerMode: off
  redis:
    ssl: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwkSetUri: http://authentication.production:8080/authentication/api/v1/.well-known/jwks.json

springfox:
  documentation:
    swaggerUi:
      enabled: false
