aws:
  cloudFront:
    distributionId:
    url:
    publicKeyId:
    privateKey:
    signatureDuration: 5h
  s3:
    bucketName:
    signatureDuration: 30m

encrypt:
  key:
  salt:

kafka:
  topic:
    "[sample.created]":
      partitions: 5
    "[sample.updated]":
      partitions: 3
    "[sample.deleted]":
      partitions: 2

logging:
  level:
    liquibase.util: ERROR
    org.apache.kafka: ERROR
    # Disable warning messages from spring retry bean configurations.
    org.springframework.context.support.PostProcessorRegistrationDelegate: ERROR

management:
  endpoint:
    health:
      showDetails: ALWAYS
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
  cloudwatch:
    metrics:
      export:
        namespace: Java/SpringBoot/${name}
  zipkin:
    tracing:
      endpoint:

server:
  error:
    whitelabel:
      enabled: false
  http2:
    enabled: true
  port: 80

spring:
  ai:
    chat:
      memory:
        repository:
          jdbc:
            initializeSchema: NEVER
    ollama:
      chat:
        model: llama3.1
      embedding:
        model: all-minilm
  application:
    name: ${name}
    version: ${version}
  cache:
    type: REDIS
    redis:
      timeToLive: 5h
  cloud:
    openfeign:
      client:
        config:
          petStore:
            url: https://petstore.swagger.io
    refresh:
      enabled: false
  data:
    redis:
      host:
      port:
      ssl:
        enabled: true
      username:
      password:
      repositories:
        enabled: false
  datasource:
    primary:
      poolName: Primary
      jdbcUrl:
      username: \${spring.datasource.username}
      password: \${spring.datasource.password}
    readOnly:
      poolName: Read-only
      readOnly: true
      jdbcUrl:
      username: \${spring.datasource.username}
      password: \${spring.datasource.password}
    username:
    password:
  elasticsearch:
    uris:
    username:
    password:
  jackson:
    defaultPropertyInclusion: NON_ABSENT
  jdbc:
    template:
      fetchSize: 100
  kafka:
    bootstrapServers:
    clientId: ${name}
    consumer:
      groupId: ${name}
      properties:
        partition:
          assignment:
            strategy: org.apache.kafka.clients.consumer.CooperativeStickyAssignor
    jaas:
      enabled: true
      loginModule: org.apache.kafka.common.security.scram.ScramLoginModule
      options:
        username:
        password:
    listener:
      ackMode: RECORD
      observationEnabled: true
    producer:
      acks: all
    properties:
      sasl:
        mechanism: SCRAM-SHA-256
    security:
      protocol: SASL_SSL
    template:
      observationEnabled: true
  main:
    bannerMode: LOG
  messages:
    basename: messages.access, messages.error, messages.validation
  mvc:
    async:
      requestTimeout: -1
    logResolvedException: false
  threads:
    virtual:
      enabled: true

springdoc:
  trimKotlinIndent: true
  openApi:
    info:
      extensions:
        x-template-group: spring
    servers:
      - url: http://localhost
        description: Local
      - url: https://api.dev.leijendary.com
        description: Development
      - url: https://api.test.leijendary.com
        description: Testing
      - url: https://api.sandbox.leijendary.com
        description: Sandbox
      - url: https://api.leijendary.com
        description: Production
    components:
      securitySchemes:
        oauth2:
          type: oauth2
          flows:
            implicit:
              authorizationUrl: https://leijendary.eu.auth0.com/authorize
              scopes:
                sample.admin.read: Read sample records as an admin
                sample.admin.write: Create sample records as an admin
                sample.admin.image.write: Upload or delete sample images as an admin
                sample.read: Read sample records
                sample.search.read: Search sample records
                sample.search.write: Reindex sample records
                image.write: Upload/validate images
                ai.chat.read: Read AI chat details or history
                ai.chat.write: Create or send chat messages to AI
  groupConfigs:
    - group: sample.v1
      pathsToMatch: /api/v1/samples/**
      openApi:
        info:
          title: Sample v1
          description: Sample API that is made for the end users/customers.
          version: 1.0.0
        servers:
          - url: /api/v1
    - group: sample.v2
      pathsToMatch: /api/v2/samples/**
      openApi:
        info:
          title: Sample v2
          description: Sample API that is made for the end users/customers.
          version: 2.0.0
        servers:
          - url: /api/v2
    - group: image.v1
      pathsToMatch: /api/v1/images/**
      openApi:
        info:
          title: Image v1
          description: Image management API.
          version: 1.0.0
        servers:
          - url: /api/v1
    - group: ai.chat.v1
      pathsToMatch: /api/v1/ai/chat/**
      openApi:
        info:
          title: AI Chat v1
          description: AI Chat related APIs.
          version: 1.0.0
        servers:
          - url: /api/v1
