auth:
  audience: https://development.leijendary.com

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwkSetUri: http://authentication.development:8080/authentication/api/v1/.well-known/jwks.json