management:
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
    tracing:
      endpoint: http://localhost:4318/v1/traces
  tracing:
    sampling:
      probability: 1.0

spring:
  cloud:
    aws:
      cloudFront:
        distributionId:
        url: https://cdn.dev.leijendary.com
      s3:
        bucketName: leijendary-api-dev
  data:
    redis:
      ssl:
        enabled: false
  datasource:
    primary:
      poolSize: 5
    readOnly:
      poolSize: 5
  kafka:
    jaas:
      enabled: false
    properties:
      sasl:
        mechanism: PLAIN
    security:
      protocol: PLAINTEXT
