spring:
  cloud:
    aws:
      cloudwatch:
        enabled: false
      s3:
        enabled: false
  data:
    jdbc:
      dialect: postgresql
  datasource:
    primary:
      allowPoolSuspension: true
    readOnly:
      allowPoolSuspension: true
  liquibase:
    enabled: false
  sql:
    init:
      mode: NEVER
