server:
  port: 8443

management:
  endpoint:
    health:
      showDetails: ALWAYS

logging:
  level:
    io:
      netty:
        resolver:
          dns:
            DnsServerAddressStreamProviders: OFF