auth:
  audience: https://staging.leijendary.com

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwkSetUri: http://authentication.staging:8080/authentication/api/v1/.well-known/jwks.json