aws:
  cloudFront:
    distributionId:
    url: https://cdn.leijendary.com
  s3:
    bucketName: leijendary-api-prod

spring:
  cloud:
    openfeign:
      httpclient:
        maxConnections: 1000
  datasource:
    primary:
      maximumPoolSize: 500
    readOnly:
      maximumPoolSize: 1000

springdoc:
  apiDocs:
    enabled: false
  swaggerUi:
    enabled: false
