apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-template-config
  namespace: template
data:
  SPRING_DATASOURCE_PRIMARY_JDBC_URL: "jdbc:postgresql://postgres-service.database.svc.cluster.local:5432/spring_template"
  SPRING_DATASOURCE_PRIMARY_USERNAME: postgres
  SPRING_DATASOURCE_READONLY_JDBC_URL: "jdbc:postgresql://postgres-service.database.svc.cluster.local:5432/spring_template"
  SPRING_DATASOURCE_READONLY_USERNAME: postgres
  SPRING_PROFILES_ACTIVE: dev,aws
  SPRING_CLOUD_AWS_CREDENTIALS_INSTANCE_PROFILE: "false"
  SPRING_CLOUD_AWS_REGION_INSTANCE_PROFILE: "false"
  SPRING_CLOUD_AWS_REGION_STATIC: me-south-1
  SPRING_ELASTICSEARCH_URIS: http://elasticsearch-service.elasticstack.svc.cluster.local:9200
  SPRING_ELASTICSEARCH_USERNAME: elastic
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-service.kafka.svc.cluster.local:9092
  SPRING_DATA_REDIS_HOST: redis-service.cache.svc.cluster.local
  SPRING_DATA_REDIS_PORT: "6379"
  AWS_EC2_METADATA_DISABLED: "true"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin-service.monitoring.svc.cluster.local:9411/api/v2/spans
