apiVersion: v1
kind: Secret
metadata:
  name: spring-template-secret
  namespace: template
type: Opaque
data:
  # 12345678
  SPRING_DATASOURCE_PRIMARY_PASSWORD: MTIzNDU2Nzg=
  # 12345678
  SPRING_DATASOURCE_READONLY_PASSWORD: MTIzNDU2Nzg=
  ENCRYPT_KEY:
  ENCRYPT_SALT:
  CLOUD_AWS_CREDENTIALS_ACCESS_KEY:
  CLOUD_AWS_CREDENTIALS_SECRET_KEY: