apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-template
  namespace: template
  labels:
    app: spring-template
spec:
  selector:
    matchLabels:
      app: spring-template
  template:
    metadata:
      labels:
        app: spring-template
    spec:
      containers:
        - name: spring-template
          image: jleijendekker/spring-template:1.0.0
          ports:
            - containerPort: 443
            - containerPort: 1099
          envFrom:
            - configMapRef:
                name: spring-template-config
            - secretRef:
                name: spring-template-secret
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /actuator/health
              port: 443
            initialDelaySeconds: 20
            timeoutSeconds: 15
            periodSeconds: 30
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /actuator/health
              port: 443
            initialDelaySeconds: 30
            timeoutSeconds: 15
            periodSeconds: 30
            failureThreshold: 3
            successThreshold: 1
          resources:
            requests:
              memory: 1G
              cpu: 0.5
            limits:
              memory: 1G
              cpu: 0.5

---
apiVersion: v1
kind: Service
metadata:
  name: spring-template-service
  namespace: template
spec:
  selector:
    app: spring-template
  type: NodePort
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30445
    - name: jmx
      protocol: TCP
      port: 1099
      targetPort: 1099
      nodePort: 30299
