apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-template
  namespace: template
  labels:
    app: spring-template
spec:
  selector:
    matchLabels:
      app: spring-template
  template:
    metadata:
      labels:
        app: spring-template
    spec:
      containers:
        - name: spring-template
          image: jleijendekker/spring-template:2.0.0
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: spring-template-config
            - secretRef:
                name: spring-template-secret
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 120
            timeoutSeconds: 5
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 150
            timeoutSeconds: 5
            periodSeconds: 15
            failureThreshold: 3
            successThreshold: 1
          resources:
            requests:
              memory: 512M
              cpu: 0.25
            limits:
              memory: 512M
              cpu: 0.25

---
apiVersion: v1
kind: Service
metadata:
  name: spring-template-service
  namespace: template
spec:
  selector:
    app: spring-template
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
