apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-template
  namespace: template
  labels:
    app: spring-template
spec:
  selector:
    matchLabels:
      app: spring-template
  template:
    metadata:
      labels:
        app: spring-template
    spec:
      containers:
        - name: spring-template
          image: spring-template:1.0.0
          ports:
            - containerPort: 443
          envFrom:
            - configMapRef:
                name: spring-template-config
            - secretRef:
                name: spring-template-secret
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /actuator/health
              port: 443
            initialDelaySeconds: 200
            timeoutSeconds: 5
            periodSeconds: 15
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /actuator/health
              port: 443
            initialDelaySeconds: 300
            timeoutSeconds: 5
            periodSeconds: 15
            failureThreshold: 3
            successThreshold: 1
          resources:
            requests:
              memory: 512M
              cpu: 0.25
            limits:
              memory: 512M
              cpu: 0.25

---
apiVersion: v1
kind: Service
metadata:
  name: spring-template-service
  namespace: template
spec:
  selector:
    app: spring-template
  type: NodePort
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30443
