apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: spring-template-autoscaler
spec:
  scaleTargetRef:
    kind: Deployment
    name: spring-template
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageValue: 358M
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageValue: 50