/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.leijendary.schema;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@org.apache.avro.specific.AvroGenerated
public class SampleTranslationSchema extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1289945070382713208L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SampleTranslationSchema\",\"namespace\":\"com.leijendary.schema\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"description\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"language\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"ordinal\",\"type\":\"int\"},{\"name\":\"createdDate\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"createdBy\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"lastModifiedDate\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"lastModifiedBy\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<SampleTranslationSchema> ENCODER =
      new BinaryMessageEncoder<SampleTranslationSchema>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<SampleTranslationSchema> DECODER =
      new BinaryMessageDecoder<SampleTranslationSchema>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<SampleTranslationSchema> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<SampleTranslationSchema> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<SampleTranslationSchema> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<SampleTranslationSchema>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this SampleTranslationSchema to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a SampleTranslationSchema from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a SampleTranslationSchema instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static SampleTranslationSchema fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private long id;
   private java.lang.String name;
   private java.lang.String description;
   private java.lang.String language;
   private int ordinal;
   private java.lang.String createdDate;
   private java.lang.String createdBy;
   private java.lang.String lastModifiedDate;
   private java.lang.String lastModifiedBy;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SampleTranslationSchema() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param name The new value for name
   * @param description The new value for description
   * @param language The new value for language
   * @param ordinal The new value for ordinal
   * @param createdDate The new value for createdDate
   * @param createdBy The new value for createdBy
   * @param lastModifiedDate The new value for lastModifiedDate
   * @param lastModifiedBy The new value for lastModifiedBy
   */
  public SampleTranslationSchema(java.lang.Long id, java.lang.String name, java.lang.String description, java.lang.String language, java.lang.Integer ordinal, java.lang.String createdDate, java.lang.String createdBy, java.lang.String lastModifiedDate, java.lang.String lastModifiedBy) {
    this.id = id;
    this.name = name;
    this.description = description;
    this.language = language;
    this.ordinal = ordinal;
    this.createdDate = createdDate;
    this.createdBy = createdBy;
    this.lastModifiedDate = lastModifiedDate;
    this.lastModifiedBy = lastModifiedBy;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return name;
    case 2: return description;
    case 3: return language;
    case 4: return ordinal;
    case 5: return createdDate;
    case 6: return createdBy;
    case 7: return lastModifiedDate;
    case 8: return lastModifiedBy;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: name = value$ != null ? value$.toString() : null; break;
    case 2: description = value$ != null ? value$.toString() : null; break;
    case 3: language = value$ != null ? value$.toString() : null; break;
    case 4: ordinal = (java.lang.Integer)value$; break;
    case 5: createdDate = value$ != null ? value$.toString() : null; break;
    case 6: createdBy = value$ != null ? value$.toString() : null; break;
    case 7: lastModifiedDate = value$ != null ? value$.toString() : null; break;
    case 8: lastModifiedBy = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public long getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.String getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'description' field.
   * @return The value of the 'description' field.
   */
  public java.lang.String getDescription() {
    return description;
  }


  /**
   * Sets the value of the 'description' field.
   * @param value the value to set.
   */
  public void setDescription(java.lang.String value) {
    this.description = value;
  }

  /**
   * Gets the value of the 'language' field.
   * @return The value of the 'language' field.
   */
  public java.lang.String getLanguage() {
    return language;
  }


  /**
   * Sets the value of the 'language' field.
   * @param value the value to set.
   */
  public void setLanguage(java.lang.String value) {
    this.language = value;
  }

  /**
   * Gets the value of the 'ordinal' field.
   * @return The value of the 'ordinal' field.
   */
  public int getOrdinal() {
    return ordinal;
  }


  /**
   * Sets the value of the 'ordinal' field.
   * @param value the value to set.
   */
  public void setOrdinal(int value) {
    this.ordinal = value;
  }

  /**
   * Gets the value of the 'createdDate' field.
   * @return The value of the 'createdDate' field.
   */
  public java.lang.String getCreatedDate() {
    return createdDate;
  }


  /**
   * Sets the value of the 'createdDate' field.
   * @param value the value to set.
   */
  public void setCreatedDate(java.lang.String value) {
    this.createdDate = value;
  }

  /**
   * Gets the value of the 'createdBy' field.
   * @return The value of the 'createdBy' field.
   */
  public java.lang.String getCreatedBy() {
    return createdBy;
  }


  /**
   * Sets the value of the 'createdBy' field.
   * @param value the value to set.
   */
  public void setCreatedBy(java.lang.String value) {
    this.createdBy = value;
  }

  /**
   * Gets the value of the 'lastModifiedDate' field.
   * @return The value of the 'lastModifiedDate' field.
   */
  public java.lang.String getLastModifiedDate() {
    return lastModifiedDate;
  }


  /**
   * Sets the value of the 'lastModifiedDate' field.
   * @param value the value to set.
   */
  public void setLastModifiedDate(java.lang.String value) {
    this.lastModifiedDate = value;
  }

  /**
   * Gets the value of the 'lastModifiedBy' field.
   * @return The value of the 'lastModifiedBy' field.
   */
  public java.lang.String getLastModifiedBy() {
    return lastModifiedBy;
  }


  /**
   * Sets the value of the 'lastModifiedBy' field.
   * @param value the value to set.
   */
  public void setLastModifiedBy(java.lang.String value) {
    this.lastModifiedBy = value;
  }

  /**
   * Creates a new SampleTranslationSchema RecordBuilder.
   * @return A new SampleTranslationSchema RecordBuilder
   */
  public static com.leijendary.schema.SampleTranslationSchema.Builder newBuilder() {
    return new com.leijendary.schema.SampleTranslationSchema.Builder();
  }

  /**
   * Creates a new SampleTranslationSchema RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SampleTranslationSchema RecordBuilder
   */
  public static com.leijendary.schema.SampleTranslationSchema.Builder newBuilder(com.leijendary.schema.SampleTranslationSchema.Builder other) {
    if (other == null) {
      return new com.leijendary.schema.SampleTranslationSchema.Builder();
    } else {
      return new com.leijendary.schema.SampleTranslationSchema.Builder(other);
    }
  }

  /**
   * Creates a new SampleTranslationSchema RecordBuilder by copying an existing SampleTranslationSchema instance.
   * @param other The existing instance to copy.
   * @return A new SampleTranslationSchema RecordBuilder
   */
  public static com.leijendary.schema.SampleTranslationSchema.Builder newBuilder(com.leijendary.schema.SampleTranslationSchema other) {
    if (other == null) {
      return new com.leijendary.schema.SampleTranslationSchema.Builder();
    } else {
      return new com.leijendary.schema.SampleTranslationSchema.Builder(other);
    }
  }

  /**
   * RecordBuilder for SampleTranslationSchema instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SampleTranslationSchema>
    implements org.apache.avro.data.RecordBuilder<SampleTranslationSchema> {

    private long id;
    private java.lang.String name;
    private java.lang.String description;
    private java.lang.String language;
    private int ordinal;
    private java.lang.String createdDate;
    private java.lang.String createdBy;
    private java.lang.String lastModifiedDate;
    private java.lang.String lastModifiedBy;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.leijendary.schema.SampleTranslationSchema.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.description)) {
        this.description = data().deepCopy(fields()[2].schema(), other.description);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.language)) {
        this.language = data().deepCopy(fields()[3].schema(), other.language);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.ordinal)) {
        this.ordinal = data().deepCopy(fields()[4].schema(), other.ordinal);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.createdDate)) {
        this.createdDate = data().deepCopy(fields()[5].schema(), other.createdDate);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.createdBy)) {
        this.createdBy = data().deepCopy(fields()[6].schema(), other.createdBy);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.lastModifiedDate)) {
        this.lastModifiedDate = data().deepCopy(fields()[7].schema(), other.lastModifiedDate);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.lastModifiedBy)) {
        this.lastModifiedBy = data().deepCopy(fields()[8].schema(), other.lastModifiedBy);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
    }

    /**
     * Creates a Builder by copying an existing SampleTranslationSchema instance
     * @param other The existing instance to copy.
     */
    private Builder(com.leijendary.schema.SampleTranslationSchema other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.description)) {
        this.description = data().deepCopy(fields()[2].schema(), other.description);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.language)) {
        this.language = data().deepCopy(fields()[3].schema(), other.language);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.ordinal)) {
        this.ordinal = data().deepCopy(fields()[4].schema(), other.ordinal);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.createdDate)) {
        this.createdDate = data().deepCopy(fields()[5].schema(), other.createdDate);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.createdBy)) {
        this.createdBy = data().deepCopy(fields()[6].schema(), other.createdBy);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.lastModifiedDate)) {
        this.lastModifiedDate = data().deepCopy(fields()[7].schema(), other.lastModifiedDate);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.lastModifiedBy)) {
        this.lastModifiedBy = data().deepCopy(fields()[8].schema(), other.lastModifiedBy);
        fieldSetFlags()[8] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public long getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.leijendary.schema.SampleTranslationSchema.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.leijendary.schema.SampleTranslationSchema.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.String getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.leijendary.schema.SampleTranslationSchema.Builder setName(java.lang.String value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.leijendary.schema.SampleTranslationSchema.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'description' field.
      * @return The value.
      */
    public java.lang.String getDescription() {
      return description;
    }


    /**
      * Sets the value of the 'description' field.
      * @param value The value of 'description'.
      * @return This builder.
      */
    public com.leijendary.schema.SampleTranslationSchema.Builder setDescription(java.lang.String value) {
      validate(fields()[2], value);
      this.description = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'description' field has been set.
      * @return True if the 'description' field has been set, false otherwise.
      */
    public boolean hasDescription() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'description' field.
      * @return This builder.
      */
    public com.leijendary.schema.SampleTranslationSchema.Builder clearDescription() {
      description = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'language' field.
      * @return The value.
      */
    public java.lang.String getLanguage() {
      return language;
    }


    /**
      * Sets the value of the 'language' field.
      * @param value The value of 'language'.
      * @return This builder.
      */
    public com.leijendary.schema.SampleTranslationSchema.Builder setLanguage(java.lang.String value) {
      validate(fields()[3], value);
      this.language = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'language' field has been set.
      * @return True if the 'language' field has been set, false otherwise.
      */
    public boolean hasLanguage() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'language' field.
      * @return This builder.
      */
    public com.leijendary.schema.SampleTranslationSchema.Builder clearLanguage() {
      language = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'ordinal' field.
      * @return The value.
      */
    public int getOrdinal() {
      return ordinal;
    }


    /**
      * Sets the value of the 'ordinal' field.
      * @param value The value of 'ordinal'.
      * @return This builder.
      */
    public com.leijendary.schema.SampleTranslationSchema.Builder setOrdinal(int value) {
      validate(fields()[4], value);
      this.ordinal = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'ordinal' field has been set.
      * @return True if the 'ordinal' field has been set, false otherwise.
      */
    public boolean hasOrdinal() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'ordinal' field.
      * @return This builder.
      */
    public com.leijendary.schema.SampleTranslationSchema.Builder clearOrdinal() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdDate' field.
      * @return The value.
      */
    public java.lang.String getCreatedDate() {
      return createdDate;
    }


    /**
      * Sets the value of the 'createdDate' field.
      * @param value The value of 'createdDate'.
      * @return This builder.
      */
    public com.leijendary.schema.SampleTranslationSchema.Builder setCreatedDate(java.lang.String value) {
      validate(fields()[5], value);
      this.createdDate = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'createdDate' field has been set.
      * @return True if the 'createdDate' field has been set, false otherwise.
      */
    public boolean hasCreatedDate() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'createdDate' field.
      * @return This builder.
      */
    public com.leijendary.schema.SampleTranslationSchema.Builder clearCreatedDate() {
      createdDate = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdBy' field.
      * @return The value.
      */
    public java.lang.String getCreatedBy() {
      return createdBy;
    }


    /**
      * Sets the value of the 'createdBy' field.
      * @param value The value of 'createdBy'.
      * @return This builder.
      */
    public com.leijendary.schema.SampleTranslationSchema.Builder setCreatedBy(java.lang.String value) {
      validate(fields()[6], value);
      this.createdBy = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'createdBy' field has been set.
      * @return True if the 'createdBy' field has been set, false otherwise.
      */
    public boolean hasCreatedBy() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'createdBy' field.
      * @return This builder.
      */
    public com.leijendary.schema.SampleTranslationSchema.Builder clearCreatedBy() {
      createdBy = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastModifiedDate' field.
      * @return The value.
      */
    public java.lang.String getLastModifiedDate() {
      return lastModifiedDate;
    }


    /**
      * Sets the value of the 'lastModifiedDate' field.
      * @param value The value of 'lastModifiedDate'.
      * @return This builder.
      */
    public com.leijendary.schema.SampleTranslationSchema.Builder setLastModifiedDate(java.lang.String value) {
      validate(fields()[7], value);
      this.lastModifiedDate = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'lastModifiedDate' field has been set.
      * @return True if the 'lastModifiedDate' field has been set, false otherwise.
      */
    public boolean hasLastModifiedDate() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'lastModifiedDate' field.
      * @return This builder.
      */
    public com.leijendary.schema.SampleTranslationSchema.Builder clearLastModifiedDate() {
      lastModifiedDate = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastModifiedBy' field.
      * @return The value.
      */
    public java.lang.String getLastModifiedBy() {
      return lastModifiedBy;
    }


    /**
      * Sets the value of the 'lastModifiedBy' field.
      * @param value The value of 'lastModifiedBy'.
      * @return This builder.
      */
    public com.leijendary.schema.SampleTranslationSchema.Builder setLastModifiedBy(java.lang.String value) {
      validate(fields()[8], value);
      this.lastModifiedBy = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'lastModifiedBy' field has been set.
      * @return True if the 'lastModifiedBy' field has been set, false otherwise.
      */
    public boolean hasLastModifiedBy() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'lastModifiedBy' field.
      * @return This builder.
      */
    public com.leijendary.schema.SampleTranslationSchema.Builder clearLastModifiedBy() {
      lastModifiedBy = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public SampleTranslationSchema build() {
      try {
        SampleTranslationSchema record = new SampleTranslationSchema();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.String) defaultValue(fields()[1]);
        record.description = fieldSetFlags()[2] ? this.description : (java.lang.String) defaultValue(fields()[2]);
        record.language = fieldSetFlags()[3] ? this.language : (java.lang.String) defaultValue(fields()[3]);
        record.ordinal = fieldSetFlags()[4] ? this.ordinal : (java.lang.Integer) defaultValue(fields()[4]);
        record.createdDate = fieldSetFlags()[5] ? this.createdDate : (java.lang.String) defaultValue(fields()[5]);
        record.createdBy = fieldSetFlags()[6] ? this.createdBy : (java.lang.String) defaultValue(fields()[6]);
        record.lastModifiedDate = fieldSetFlags()[7] ? this.lastModifiedDate : (java.lang.String) defaultValue(fields()[7]);
        record.lastModifiedBy = fieldSetFlags()[8] ? this.lastModifiedBy : (java.lang.String) defaultValue(fields()[8]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<SampleTranslationSchema>
    WRITER$ = (org.apache.avro.io.DatumWriter<SampleTranslationSchema>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<SampleTranslationSchema>
    READER$ = (org.apache.avro.io.DatumReader<SampleTranslationSchema>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.id);

    out.writeString(this.name);

    out.writeString(this.description);

    out.writeString(this.language);

    out.writeInt(this.ordinal);

    out.writeString(this.createdDate);

    out.writeString(this.createdBy);

    out.writeString(this.lastModifiedDate);

    out.writeString(this.lastModifiedBy);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readLong();

      this.name = in.readString();

      this.description = in.readString();

      this.language = in.readString();

      this.ordinal = in.readInt();

      this.createdDate = in.readString();

      this.createdBy = in.readString();

      this.lastModifiedDate = in.readString();

      this.lastModifiedBy = in.readString();

    } else {
      for (int i = 0; i < 9; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readLong();
          break;

        case 1:
          this.name = in.readString();
          break;

        case 2:
          this.description = in.readString();
          break;

        case 3:
          this.language = in.readString();
          break;

        case 4:
          this.ordinal = in.readInt();
          break;

        case 5:
          this.createdDate = in.readString();
          break;

        case 6:
          this.createdBy = in.readString();
          break;

        case 7:
          this.lastModifiedDate = in.readString();
          break;

        case 8:
          this.lastModifiedBy = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










