on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  binary:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: ${{ inputs.environment }}
    steps:
      - name: Setup java 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: "zulu"
      - name: Setup gradle
        uses: gradle/gradle-build-action@v2
      - name: Checkout
        uses: actions/checkout@v3
      - name: Execute gradle build
        run: ./gradlew bootJar -i -x test
      - name: Upload dockerfile
        uses: actions/upload-artifact@v3
        with:
          name: dockerfile
          path: Dockerfile
          retention-days: 5
          if-no-files-found: error
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: binary
          path: build/libs/*.jar
          retention-days: 5
          if-no-files-found: error
  push:
    needs: binary
    runs-on: ubuntu-latest
    timeout-minutes: 2
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/DeploymentRole-${{ inputs.environment }}
      - id: login-registry
        name: Login to registry
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: "true"
      - name: Download dockerfile
        uses: actions/download-artifact@v3
        with:
          name: dockerfile
      - name: Download binary
        uses: actions/download-artifact@v3
        with:
          name: binary
          path: build/libs
      - name: Push to registry
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          tags: ${{ steps.login-registry.outputs.registry }}/${{ github.event.repository.name }}:${{ github.sha }}
          push: true
