on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      image-tag:
        required: false
        type: string
        default: ${{ github.sha }}

permissions:
  id-token: write
  contents: read

jobs:
  docker:
    name: Docker
    runs-on: macos-14
    timeout-minutes: 120
    environment: ${{ inputs.environment }}
    steps:
      - name: Setup Docker
        run: |
          brew install docker colima lima
          colima version
          colima start --cpu 3 --memory 6 --disk 100 --vm-type=qemu --mount-type=sshfs --dns=1.1.1.1
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm64
      - name: Setup Gradle (for caching)
        uses: gradle/actions/setup-gradle@v3
      - name: Checkout
        uses: actions/checkout@v4
      - name: Copy Gradle dependencies
        run: cp -R ~/.gradle .gradle/
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/DeploymentRole-${{ inputs.environment }}
      - id: login-registry
        name: Login to registry
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: true
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          build-args: |
            SPRING_PROFILES_ACTIVE=${{ inputs.environment }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          platforms: linux/arm64
          push: true
          tags: ${{ steps.login-registry.outputs.registry }}/${{ github.event.repository.name }}:${{ inputs.image-tag }}
