on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - id: login-ecr
        name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and push
        uses: docker/build-push-action@v4
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ github.event.repository.name }}
          IMAGE_TAG: ${{ github.sha }}
          DOCKER_BUILDKIT: 1
        with:
          context: .
          platforms: linux/arm64
          build-args: BUILDKIT_INLINE_CACHE=1
          cache-from: $REGISTRY/$REPOSITORY:latest
          tags: |
            $REGISTRY/$REPOSITORY:$IMAGE_TAG
            $REGISTRY/$REPOSITORY:latest
          push: true
