name: Build

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      image-tag:
        required: false
        type: string
        default: ${{ github.sha }}

permissions:
  id-token: write
  contents: read

jobs:
  docker:
    name: Docker
    runs-on: codebuild-${{ github.event.repository.name }}-${{ inputs.environment }}-${{ github.run_id }}-${{ github.run_attempt }}-arm-3.0-large
    timeout-minutes: 30
    environment: ${{ inputs.environment }}
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm64
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/DeploymentRole-${{ inputs.environment }}
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: ${{ secrets.AWS_ECR_ACCOUNT_ID }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/arm64
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ github.event.repository.name }}:${{ inputs.image-tag }}
