on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    timeout-minutes: 120
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm64
      - name: Setup Gradle (for caching)
        uses: gradle/gradle-build-action@v2
      - name: Checkout
        uses: actions/checkout@v3
      - name: Copy Gradle dependencies
        run: cp -R ~/.gradle .gradle/
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/DeploymentRole-${{ inputs.environment }}
      - id: login-registry
        name: Login to registry
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: "true"
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          build-args:
            SPRING_PROFILES_ACTIVE=${{ inputs.environment }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          platforms: linux/arm64
          push: true
          tags: ${{ steps.login-registry.outputs.registry }}/${{ github.event.repository.name }}:${{ github.sha }}
