on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  binary:
    runs-on: codebuild-${{ github.event.repository.name }}-${{ inputs.environment }}-${{ github.run_id }}-${{ github.run_attempt }}-arm-3.0-large
    timeout-minutes: 30
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          distribution: graalvm-community
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false
      - name: Execute Gradle compile
        run: SPRING_PROFILES_ACTIVE=${{ inputs.environment }} ./gradlew nativeCompile -i -x test
      - name: Upload Dockerfile
        uses: actions/upload-artifact@v4
        with:
          name: dockerfile
          path: Dockerfile
          retention-days: 5
          if-no-files-found: error
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: binary
          path: build/native/nativeCompile/app
          retention-days: 5
          if-no-files-found: error
  push:
    needs: binary
    runs-on: ubuntu-latest
    timeout-minutes: 2
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm64
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/DeploymentRole-${{ inputs.environment }}
      - id: login-registry
        name: Login to registry
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: true
      - name: Download Dockerfile
        uses: actions/download-artifact@v4
        with:
          name: dockerfile
      - name: Download binary
        uses: actions/download-artifact@v4
        with:
          name: binary
          path: build/native/nativeCompile
      - id: metadata
        name: Metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.login-registry.outputs.registry }}/${{ github.event.repository.name }}
          tags: |
            type=semver,pattern={{version}}
            type=sha,prefix=,format=long
      - name: Push to registry
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
