name: CI/CD

on:
  push:
    branches:
      - main
      - release/*

concurrency:
  group: ci
  cancel-in-progress: true

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    secrets: inherit
  deploy:
    needs: build
    name: Deploy (dev)
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: dev
    secrets: inherit
