name: CI/CD

on:
  push:
    branches:
      - main
      - release/*

concurrency:
  group: ci
  cancel-in-progress: true

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    secrets: inherit
  deploy:
    needs: build
    strategy:
      max-parallel: 1
      matrix:
        environment:
          - test
          - prod
    name: Deploy to ${{ matrix.environment }}
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: ${{ matrix.environment }}
      version: ${{ needs.build.outputs.version }}
    secrets: inherit
