name: Push on tags

on:
  push:
    tags:
      - "*"

concurrency:
  group: tag
  cancel-in-progress: true

jobs:
  # Sandbox environment
  build-sandbox:
    name: Build sandbox
    uses: ./.github/workflows/build.yaml
    with:
      environment: sandbox
    secrets: inherit
  deploy-sandbox:
    needs: build-sandbox
    name: Deploy sandbox
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: sandbox
      image-tag: ${{ github.ref_name }}
    secrets: inherit

  # Production environment
  build-prod:
    name: Build production
    uses: ./.github/workflows/build.yaml
    with:
      environment: prod
    secrets: inherit
  deploy-prod:
    needs: build-prod
    name: Deploy production
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: prod
      image-tag: ${{ github.ref_name }}
    secrets: inherit
