on:
  push:
    branches:
      - feature/**
      - fix/**
      - hotfix/**

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yaml
    with:
      environment: dev
    secrets: inherit
