on:
  push:
    tags:
      - "*"

concurrency:
  group: tag
  cancel-in-progress: true

jobs:
  # Sandbox environment
  tag-sandbox:
    name: Tag sandbox
    uses: ./.github/workflows/tag.yaml
    with:
      environment: sandbox
    secrets: inherit
  deploy-sandbox:
    needs: tag-sandbox
    name: Deploy sandbox
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: sandbox
      image-tag: ${{ github.ref_name }}
    secrets: inherit

  # Production environment
  tag-prod:
    needs: deploy-sandbox
    name: Tag production
    uses: ./.github/workflows/tag.yaml
    with:
      environment: prod
    secrets: inherit
  deploy-prod:
    needs: tag-prod
    name: Deploy production
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: prod
      image-tag: ${{ github.ref_name }}
    secrets: inherit
