name: Tag

on:
  push:
    tags:
      - '*'

concurrency:
  group: tag
  cancel-in-progress: true

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 5
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_BUILD_ACCOUNT_ID }}:role/BuildRole
      - id: login-ecr
        name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2
      - name: Tag and push
        env:
          REPOSITORY: ${{ steps.login-ecr.outputs.registry }}/${{ github.event.repository.name }}
        run: |
          docker pull --platform=linux/arm64 ${{ env.REPOSITORY }}:${{ github.sha }}
          docker tag ${{ env.REPOSITORY }}:${{ github.sha }} ${{ env.REPOSITORY }}:${{ github.ref_name }}
          docker push ${{ env.REPOSITORY }}:${{ github.ref_name }}
  deploy:
    needs: docker
    name: Deploy to prod
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: prod
      version: ${{ github.ref_name }}
    secrets: inherit
