on:
  push:
    tags:
      - "*"

jobs:
  test-staging:
    name: Test
    uses: ./.github/workflows/test.yaml
    with:
      environment: staging
    secrets: inherit
  test-prod:
    name: Test
    uses: ./.github/workflows/test.yaml
    with:
      environment: prod
    secrets: inherit
  build-staging:
    needs: test-staging
    name: Build
    uses: ./.github/workflows/build.yaml
    with:
      environment: staging
      image-tag: ${{ github.ref_name }}
    secrets: inherit
  build-prod:
    needs: test-prod
    name: Build
    uses: ./.github/workflows/build.yaml
    with:
      environment: prod
      image-tag: ${{ github.ref_name }}
    secrets: inherit
  deploy-staging:
    needs: build-staging
    name: Deploy
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: staging
      image-tag: ${{ github.ref_name }}
    secrets: inherit
  deploy-prod:
    needs: build-prod
    name: Deploy
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: prod
      image-tag: ${{ github.ref_name }}
    secrets: inherit
