on:
  push:
    tags:
      - "*"

jobs:
  test-staging:
    name: Test staging
    uses: ./.github/workflows/test.yaml
    with:
      environment: staging
    secrets: inherit
  test-prod:
    name: Test production
    uses: ./.github/workflows/test.yaml
    with:
      environment: prod
    secrets: inherit
  build-staging:
    needs: test-staging
    name: Build for staging
    uses: ./.github/workflows/build.yaml
    with:
      environment: staging
      image-tag: ${{ github.ref_name }}
    secrets: inherit
  build-prod:
    needs: test-prod
    name: Build for production
    uses: ./.github/workflows/build.yaml
    with:
      environment: prod
      image-tag: ${{ github.ref_name }}
    secrets: inherit
  deploy-staging:
    needs: build-staging
    name: Deploy to staging
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: staging
      image-tag: ${{ github.ref_name }}
    secrets: inherit
  deploy-prod:
    needs: build-prod
    name: Deploy to production
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: prod
      image-tag: ${{ github.ref_name }}
    secrets: inherit
