name: Tag

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: ${{ inputs.environment }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/DeploymentRole-${{ inputs.environment }}
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: ${{ secrets.AWS_ECR_ACCOUNT_ID }}
      - name: Tag and push
        env:
          SOURCE: ${{ steps.login-ecr.outputs.registry }}/${{ github.event.repository.name }}:${{ github.sha }}
          TARGET: ${{ steps.login-ecr.outputs.registry }}/${{ github.event.repository.name }}:${{ github.ref_name }}
        run: |
          docker pull --platform=linux/arm64 ${{ env.SOURCE }}
          docker tag ${{ env.SOURCE }} ${{ env.TARGET }}
          docker push ${{ env.TARGET }}
